### ISSUE TITLE
dnf-plugin-nvidia-2.0-1 on Rocky 8 gives constant python traceback

### ISSUE THREAD

**Issue by paulraines68** [NVIDIA/yum-packaging-nvidia-plugin#10]
With dnf-plugin-nvidia-2.0-1 installed on a Rocky 8 with driver 515.65.01 anytime I run dnf I get

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/plugin.py", line 104, in _caller
    getattr(plugin, method)()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/nvidia.py", line 140, in sack
    if not kmod_pkg:
UnboundLocalError: local variable 'kmod_pkg' referenced before assignment

Happens though on only some of my Rocky 8 boxes with nvidia drivers installed.  I cannot figure out what makes the difference.

**Comment by kmittman** [comment]
Believe this is the same issue @braindevices referenced in #9 which reproduces when kmod packages are not [yet] available for a kernel+driver combination. I'll merge that pull request and generate a new set of RPMs.

**Comment by scaronni-nvidia** [comment]
@paulraines68 this is fixed in plugin 2.1-2, please test again and open another bug if you see additional issues. Thanks!
