### ISSUE TITLE
weak-deps not working anymore

### ISSUE THREAD

**Issue by zvonkok** [NVIDIA/yum-packaging-nvidia-plugin#5]
Hello, I remember using the `dnf nvidia-plugin` way back when one of the first solutions were implemented, we had added weak-deps on some packages. We could cut down the package list from ~130 to ~88 packages. A fresh install gives me again the full list of ~130 packages (fonts, gtk-update-cache, etc)

[https://hackmd.io/@mandalorian/r1q-_Y30O](https://hackmd.io/@mandalorian/r1q-_Y30O)

Are there any plans to create a compute-only version of the installation?  This is related to headless systems and container use-cases.

**Comment by kmittman** [comment]
Hi @zvonkok, we are unable to rely on weak dependencies, due to lack of a stable Linux kernel ABI. This should not affect anything other than requiring a new precompiled `nvidia-kmod` package per every kernel version string (ex:  `4.18.0-305.10.2` != `4.18.0-305.7.1` != `4.18.0-305`) and NVIDIA driver combination.

This is not a new change, so I'm not sure what you mean by "not working *anymore*".

**Comment by zvonkok** [comment]
Hello @kmittman, let me formulate my question differently with some explanations. 

In this context, I am talking about `dnf --setopt=install_weak_deps=False` which is not related to the kernel, solely on the dependency graph that `dnf` creates e.g. for a specific package like `nvidia-fabricmanager` , `nvidia-driver`.  I have been working with the RH team that implemented the first version of the `nvidia-plugin` and the very first prebuild kmods.  I requested from them to create weak_desp on RPMs that we do not need in a headless system. 

The other context is kernel `weak-updates`, RH has a stable kernel API interface, the problem we have here is that NV kernel modules are not using whitelisted symbols. Those whitelisted symbols are guaranteed to not change between RHEL minor versions. Meaning if you built a kernel module on 8.0 with only whitelisted symbols you can leverage weak-updates on 8.1, 8.x. 

 To come back to my original question, the dependency graph could be scaled down by using `dnf --setopt=install_weak_deps=False`  meaning RPM package like `abattis-cantarell-fonts` could be excluded from the install.

I hope this makes sense.

**Comment by scaronni-nvidia** [comment]
Changes are coming for headless support (it's just some reorganization of files inside the packages), but they are currently not released. I'm assigning this myself and will update it once the changes go public.

**Comment by scaronni** [comment]
@zvonkok with driver 560 you can install the following:
- A desktop system with no compute capability
- A headless system with no display or dependency on graphical components
- A desktop system with compute capabilities as well

Example for compute only:
```
dnf install nvidia-driver-cuda
```
Example for desktop only:
```
dnf install nvidia-driver
```
Example for desktop with everything:
```
dnf install nvidia-open
dnf install nvidia-driver nvidia-driver-cuda
```
Example for desktop with everything plus 32 bit libraries for games:
```
dnf install nvidia-driver nvidia-driver-cuda nvidia-driver-libs.i686
```
