### ISSUE TITLE
gpg version

### ISSUE THREAD

**Issue by rogerpeaseresi** [NVIDIA/yum-packaging-nvidia-plugin#7]
Hello- Thanks again for putting these all together. 

I've tried this with a few major releases (Centos, Ubuntu) in docker and gotten: 

[root@4d7cd71e57ff yum-packaging-nvidia-plugin]# gpg --generate-key
gpg: invalid option "--generate-key"

Can you tell me what version of gpg you are assuming? 

[root@4d7cd71e57ff yum-packaging-nvidia-plugin]# gpg --version
gpg (GnuPG) 2.0.22

**Comment by kmittman** [comment]
Hi @rogerpeaseresi yeah unfortunately the functionality of GnuPG seems to vary a lot from version to version.
CentOS 8 and Fedora 32 come with version 2.2.20 and I have version 2.3.3 on Fedora 35.
Looks like you are trying with CentOS 7, that comes with version 2.0.22 and the option is `--gen-key`

**Comment by kmittman** [comment]
The instructions for a CentOS7 container are something like this

Build the RPM package
```shell
yum install python36 rpm-build rpm-sign git
git clone -b rhel7 https://github.com/NVIDIA/yum-packaging-nvidia-plugin
cd yum-packaging-nvidia-plugin/
mkdir BUILD BUILDROOT RPMS SRPMS SOURCES SPECS
cp nvidia.conf SOURCES/
cp nvidia-yum.py SOURCES/
cp yum-plugin-nvidia.spec SPECS/
rpmbuild --define "%_topdir $(pwd)" --define "debug_package %{nil}" -v -bb SPECS/yum-plugin-nvidia.spec
```
Create a GPG key with `gpg --gen-key`
* Follow the interactive prompts for: key type, key size, key expiration
* Follow the interactive prompts for: real name, email address, comment

Sign the RPM package with your private GPG key
```shell
$ gpg --list-keys
$HOME/.gnupg/pubring.gpg
------------------------
pub   2048R/BAD21F9B 2021-12-21
uid                  First Last <name@example.com>
```
In this example, the shortname for our GPG public key is `BAD21F9B`.
```shell
export gpgKey="BAD21F9B"
gpgArgs="/usr/bin/gpg --force-v3-sigs --digest-algo=sha512 --no-verbose --no-armor --no-secmem-warning"
pkg_sign() { rpm --define "%_signature gpg" --define "%_gpg_name $gpgKey" --define "%__gpg /usr/bin/gpg" --define "%_gpg_digest_algo sha512" --define "%_binary_filedigest_algorithm 10" --define "%__gpg_sign_cmd %{__gpg} $gpgArgs -u %{_gpg_name} -sbo %{__signature_filename} %{__plaintext_filename}" --addsign "$1"; }
for package in RPMS/noarch/*-plugin-nvidia*.rpm; do pkg_sign "$package"; done
```

Instructions for creating/updating RPM repository metadata can found here:
https://github.com/NVIDIA/yum-packaging-precompiled-kmod#generate-metadata

**Comment by rogerpeaseresi** [comment]
Thanks! This seems to have gotten me quite a bit farther! If I have any more issues I'll let you know.

**Comment by kmittman** [comment]
Closing. Feel free to re-open if need further guidance.
